const titlePlaceHolder=document.getElementById("note-title"),formBtn=document.getElementById("form-buttons"),submitNoteBtn=document.getElementById("submit-button"),takeNotePlaceHolder=document.getElementById("note-text"),noteDiv=document.getElementById("notes"),closeBtn=document.getElementById("form-close-button");let modalTitle=document.getElementById("title"),modalBody=document.getElementById("text"),htmlHomeText=document.getElementById("placeholder"),titleModalValue="",bodyModalValue="";function ShowForm(){titlePlaceHolder.classList.remove("hide"),titlePlaceHolder.classList.add("show"),formBtn.classList.remove("hide"),formBtn.classList.add("show")}function clearForm(){titlePlaceHolder.value="",takeNotePlaceHolder.value=""}modalTitle.addEventListener("keyup",()=>{titleModalValue=modalTitle.value}),modalBody.addEventListener("keyup",()=>{bodyModalValue=modalBody.value});const newObject1=window.localStorage.getItem("myObject"),localStrValue=JSON.parse(newObject1);let testArray=[];function fillObject(){let e={titre:titlePlaceHolder.value,content:takeNotePlaceHolder.value};return e}function testValue(e,t,l){testArray[e]={...testArray[e],color:t};let o=l.parentElement.parentElement.parentElement;o.style.backgroundColor=t,window.localStorage.setItem("myObject",JSON.stringify(testArray))}testArray=0===localStrValue.length?[]:localStrValue;let updateGetIndice=[];function showModal(e){updateGetIndice=[e],modalTitle.placeholder=testArray[e].title,modalBody.placeholder=testArray[e].body,titleModalValue=testArray[e].title,bodyModalValue=testArray[e].body,document.getElementById("modal").classList.remove("hide"),document.getElementById("modal").classList.add("show")}function gt(e){testArray[e],modalTitle.placeholder=testArray[e].title,modalBody.placeholder=testArray[e].body;let t=testArray.indexOf(testArray[e]);-1!==t&&testArray.splice(t,1),testArray[e].title=modalTitle.value,testArray[e].body=modalBody.value,testArray[e].color=testArray[e].color}function deleteNote(e){let t=testArray.indexOf(testArray[e]);-1!==t&&(window.localStorage.clear(),testArray.splice(t,1),window.localStorage.setItem("myObject",JSON.stringify(testArray)),showMemoLocalStorage(),0===testArray.length&&(htmlHomeText.style="display:flex"))}function showMemoLocalStorage(){let e=window.localStorage.getItem("myObject"),t=JSON.parse(e),l="";t?(t.map(e=>{let o=t.indexOf(e);l+=` 
    <div style="background-color:${e.color}"  class="note">
      <div onclick="showModal(${o})" class="note-title">${e.title}</div>
      <div  onclick="showModal(${o})" class="note-text" >${e.body}</div>
        <div class="toolbar-container">
          <div class="toolbar">
              <button id="btn1" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#d1d1d1;" value="#d1d1d1""></button>
              <button id="btn2" onclick="testValue(${o},this.value,this)" class=" btn-color" style="background-color:#c2dfff;" value="#c2dfff"></button>
              <button id="btn3" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#fff9b8;" value="#fff9b8"></button>
              <button id="btn4" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#ffffff;" value="#ffffff"></button>
              <button  onclick="deleteNote(${o})" class="delete-note"  >Delete</button>
          </div>
        </div>
    </div>
    
       `}),noteDiv.innerHTML=l):console.log("localStorage is empty")}function changeColor(){let e=document.getElementsByClassName("btn-color"),t="";for(let l of e)l.addEventListener("click",()=>{t=l.value;let e=l.parentElement.parentElement.parentElement;e.style.backgroundColor=t})}document.getElementById("close-modal-btn").addEventListener("click",()=>{document.getElementById("modal").classList.remove("show"),document.getElementById("modal").classList.add("hide"),""===titleModalValue||""===bodyModalValue||(testArray[updateGetIndice].title=titleModalValue,testArray[updateGetIndice].body=bodyModalValue,window.localStorage.setItem("myObject",JSON.stringify(testArray)),showMemoLocalStorage())}),showMemoLocalStorage(),takeNotePlaceHolder.addEventListener("click",ShowForm),titlePlaceHolder.addEventListener("keyup",()=>{fillObject()}),takeNotePlaceHolder.addEventListener("keyup",()=>{fillObject()}),submitNoteBtn.addEventListener("click",e=>{e.preventDefault();let t=fillObject();""===t.titre&&""===t.content||(htmlHomeText.style="display:none",testArray.push({title:t.titre,body:t.content,color:""}),window.localStorage.setItem("myObject",JSON.stringify(testArray))),showMemoLocalStorage(),clearForm()}),closeBtn.addEventListener("click",clearForm),window.addEventListener("mouseup",e=>{e.target!=titlePlaceHolder&&e.target.parentNode!=titlePlaceHolder&&(titlePlaceHolder.classList.remove("show"),titlePlaceHolder.classList.add("hide"),formBtn.classList.remove("show"),formBtn.classList.add("hide"))}),testArray.length>0&&(htmlHomeText.style="display:none");