const titlePlaceHolder=document.getElementById("note-title"),formBtn=document.getElementById("form-buttons"),submitNoteBtn=document.getElementById("submit-button"),takeNotePlaceHolder=document.getElementById("note-text"),noteDiv=document.getElementById("notes"),closeBtn=document.getElementById("form-close-button");let modalTitle=document.getElementById("title"),modalBody=document.getElementById("text"),titleModalValue="",bodyModalValue="";function ShowForm(){titlePlaceHolder.classList.remove("hide"),titlePlaceHolder.classList.add("show"),formBtn.classList.remove("hide"),formBtn.classList.add("show")}function clearForm(){titlePlaceHolder.value="",takeNotePlaceHolder.value=""}modalTitle.addEventListener("keyup",()=>{titleModalValue=modalTitle.value}),modalBody.addEventListener("keyup",()=>{bodyModalValue=modalBody.value});const newObject1=window.localStorage.getItem("myObject"),localStrValue=JSON.parse(newObject1);let testArray=[];function fillObject(){let t={titre:titlePlaceHolder.value,content:takeNotePlaceHolder.value};return t}function testValue(t,e,l){testArray[t]={...testArray[t],color:e};let o=l.parentElement.parentElement.parentElement;o.style.backgroundColor=e,window.localStorage.setItem("myObject",JSON.stringify(testArray)),console.log(testArray)}localStrValue?testArray=localStrValue:(console.log("empty"),testArray=[]);let updateGetIndice=[];function showModal(t){updateGetIndice=[t],modalTitle.placeholder=testArray[t].title,modalBody.placeholder=testArray[t].body,titleModalValue=testArray[t].title,bodyModalValue=testArray[t].body,document.getElementById("modal").classList.remove("hide"),document.getElementById("modal").classList.add("show"),console.log(testArray)}function gt(t){testArray[t],modalTitle.placeholder=testArray[t].title,modalBody.placeholder=testArray[t].body,console.log("testArray[x]",testArray[t]),console.log("testArray",testArray);let e=testArray.indexOf(testArray[t]);-1!==e&&testArray.splice(e,1),testArray[t].title=modalTitle.value,testArray[t].body=modalBody.value,testArray[t].color=testArray[t].color,console.log("test beging",testArray)}function deleteNote(t){let e=testArray.indexOf(testArray[t]);-1!==e&&(window.localStorage.clear(),testArray.splice(e,1),window.localStorage.setItem("myObject",JSON.stringify(testArray)),showMemoLocalStorage())}function showMemoLocalStorage(){let t=window.localStorage.getItem("myObject"),e=JSON.parse(t),l="";e?(e.map(t=>{let o=e.indexOf(t);l+=` 
    <div style="background-color:${t.color}"  class="note">
      <div onclick="showModal(${o})" class="note-title">${t.title}</div>
      <div  onclick="showModal(${o})" class="note-text" >${t.body}</div>
        <div class="toolbar-container">
          <div class="toolbar">
              <button id="btn1" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#d1d1d1;" value="#d1d1d1""></button>
              <button id="btn2" onclick="testValue(${o},this.value,this)" class=" btn-color" style="background-color:#c2dfff;" value="#c2dfff"></button>
              <button id="btn3" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#fff9b8;" value="#fff9b8"></button>
              <button id="btn4" onclick="testValue(${o},this.value,this)" class="btn-color" style="background-color:#ffffff;" value="#ffffff"></button>
              <button  onclick="deleteNote(${o})" class="delete-note"  >Delete</button>
          </div>
        </div>
    </div>
    
       `}),noteDiv.innerHTML=l):console.log("localStorage is empty")}function changeColor(){let t=document.getElementsByClassName("btn-color"),e="";for(let l of t)l.addEventListener("click",()=>{e=l.value;let t=l.parentElement.parentElement.parentElement;t.style.backgroundColor=e})}document.getElementById("close-modal-btn").addEventListener("click",()=>{document.getElementById("modal").classList.remove("show"),document.getElementById("modal").classList.add("hide"),""===titleModalValue||""===bodyModalValue?console.log("rrt"):(testArray[updateGetIndice].title=titleModalValue,testArray[updateGetIndice].body=bodyModalValue,window.localStorage.setItem("myObject",JSON.stringify(testArray)),showMemoLocalStorage()),console.log("test",testArray[updateGetIndice]),console.log("ya rbi salama",testArray)}),showMemoLocalStorage(),takeNotePlaceHolder.addEventListener("click",ShowForm),titlePlaceHolder.addEventListener("keyup",()=>{fillObject()}),takeNotePlaceHolder.addEventListener("keyup",()=>{fillObject()}),submitNoteBtn.addEventListener("click",t=>{t.preventDefault();let e=fillObject();testArray.push({title:e.titre,body:e.content,color:""}),""===e.titre&&""===e.content?console.log("3amer"):window.localStorage.setItem("myObject",JSON.stringify(testArray)),showMemoLocalStorage(),clearForm()}),closeBtn.addEventListener("click",clearForm),window.addEventListener("mouseup",t=>{t.target!=titlePlaceHolder&&t.target.parentNode!=titlePlaceHolder&&(titlePlaceHolder.classList.remove("show"),titlePlaceHolder.classList.add("hide"),formBtn.classList.remove("show"),formBtn.classList.add("hide"))});